export const CHANGE_ROOM_PARAMETRS = "CHANGE_ROOM_PARAMETRS";

export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";
export const SET_CATEGORY_VALUE = "SET_CATEGORY_VALUE";

export const FETCH_CATEGORY_STATE_SUCCESS = "FETCH_CATEGORY_STATE_SUCCESS";
export const FETCH_CATEGORY_STATE_FAILURE = "FETCH_CATEGORY_STATE_FAILURE";
export const SET_CATEGORY_STATE_VALUE = "SET_CATEGORY_STATE_VALUE";
